### ISSUE TITLE
Not detecting Merged Dataset

### ISSUE THREAD

**Issue by caldiver07** [VolkovLabs/business-table#153]
If you have multiple queries that are then merged via the merge transformation, business-table is only seeing the first query and not the merged queries.

**Comment by vitPinchuk** [comment]
@caldiver07 Thank you for you question

I've created two queries.  

Display data in "Table view":
First data:
![image](https://github.com/user-attachments/assets/6d23d58b-3090-45fe-b2f6-c59ad6012e72)

Second data:
![image](https://github.com/user-attachments/assets/71a399e7-fe04-47ad-85ae-bb71dbaaaecd)

Apply transformation
![image](https://github.com/user-attachments/assets/075c4299-6ea7-4f77-a724-1f6ffe157c63)


Bussiness table shows data as expected (full merged data)

![image](https://github.com/user-attachments/assets/a898a2f1-d4c5-476d-a9db-d147a1485f9c)


I don' t see described issue. All queries display. 
Note: If you have a query. Then you have set `Layout` options. Then you added more queries and used merge. After that the data will not be displayed correctly. 

![image](https://github.com/user-attachments/assets/7c53a84d-bde9-4074-937d-001d8826b9b0)


This happens because the field IDs from the data change after the merge has occurred. 

Before Merge: 
![image](https://github.com/user-attachments/assets/8a9db108-cd0e-4829-8917-661867d1f82d)


After merge: 
![image](https://github.com/user-attachments/assets/451abcfa-18cc-4dbf-99a9-bca5d1c2769d)


In this case, the layout must be modified with new fields. 

Let me know if you find it helpful
Thank you
